---
- name: Remove existing emacs config
  file:
    path: "{{ ansible_env.HOME }}/.emacs.d"
    state: absent

- name: pull fate-emacs
  git:
    repo: git@github.com:braineo/fate-emacs.git
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    version: master
