- name: Ensure font directory exist
  file:
    path: "{{ ansible_env.HOME }}{{ font_dir }}"
    state: directory

- name: install fira code font
  unarchive:
    src: fonts/FiraCodeFonts.tar.gz
    dest: "{{ ansible_env.HOME }}{{ font_dir }}"
