---
- name: install essential node packages
  become: "{{ ansible_distribution != 'MacOSX' }}"
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
  with_items: "{{ npm_packages }}"
