---
- name: install pip2 packages
  become: "{{ ansible_distribution != 'MacOSX' }}"
  pip:
    name: "{{ pip2_packages }}"

- name: install pip3 packages
  become: "{{ ansible_distribution != 'MacOSX' }}"
  pip:
    name: "{{ pip3_packages }}"
