---
- name: copy shell configs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/"
  with_fileglob:
    - home/.*

- name: install zim
  git:
    repo: git@github.com:braineo/zimfw.git
    dest: "{{ ansible_env.HOME }}/.zim"
    version: master

- name: install bash-it
  git:
    repo: git@github.com:Bash-it/bash-it.git
    dest: "{{ ansible_env.HOME }}/.bash_it"
