---
# path are relative to home {{ ansible_env.HOME }}{{ font_dir }}
font_dir: /.local/share/fonts

apt_packages:
  - htop
  - tmux
  - git
  - tig
  - curl
  - wget
  - vim-gnome
  - rsync
  - ipython
  - python-pip
  - python3-pip
  - python-dev
  - build-essential
  - xclip
  - silversearcher-ag
  - mlocate
  - bzr
  - zsh
  - arc-theme
  - aria2
  - cinnamon-desktop-environment
  - checkinstall
  - fcitx-table-wubi
  - fcitx-mozc
  - tar
  - unzip
  - python-apt
  - clang-format-3.9
  - daemon
  - nmap
  - redis-server
  - stow
  - lnav
  - realpath
  - nodejs
  - highlight
  - tree
  - shellcheck
  - shutter
  - name: emacs25
    state: build-dep

extra_dotfiles:
  - terminator
