---
- name: add node repository signing key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add node apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "nodesource"
  with_items:
    - deb https://deb.nodesource.com/node_12.x stretch main
    - deb-src https://deb.nodesource.com/node_12.x stretch main
  when:
    - ansible_facts['distribution_major_version'] == '9'

- name: add node apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "nodesource"
  with_items:
    - deb https://deb.nodesource.com/node_12.x buster main
    - deb-src https://deb.nodesource.com/node_12.x buster main
  when:
    - ansible_facts['distribution_major_version'] == '10'

- name: install essential packages and desktop environment
  become: true
  tags: apt
  apt:
    pkg: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    update_cache: yes
  with_items: "{{ apt_packages }}"
