---
- name: pull emacs from git
  git:
    repo: git@github.com:emacs-mirror/emacs.git
    dest: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs"
    version: master

- name: create build folder for emacs
  file:
    path: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs_build"
    state: directory

- name: run emacs autogen
  command: ./autogen.sh
  args:
    chdir: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs_build"

- name: run emacs configure
  command: ../emacs/configure
  args:
    chdir: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs_build"

- name: compile emacs
  make:
    chdir: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs_build"

- name: install emacs
  become: true
  command: checkinstall --fstrans=no --pkgname emacs27 --pkgversion 27.05 -y
  args:
    chdir: "{{ ansible_env.HOME }}{{ clone_dir }}/source/emacs_build"

- name: remove dot emacs
  file:
    path: "{{ ansible_env.HOME }}/.emacs.d"
    state: absent

- name: pull spacemacs
  git:
    repo: git@github.com:braineo/spacemacs.git
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    version: develop
