---
- name: download icon set
  git:
    repo: git@github.com:LinxGem33/Arc-OSX-Icons.git
    dest: "{{ ansible_env.HOME }}{{ clone_dir }}/theme/Arc-OSX-Icons"

- name: create icon folder
  file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory

- name: copy icon set
  shell: "cp -r {{ ansible_env.HOME }}{{ clone_dir }}/theme/Arc-OSX-Icons/src/* {{ ansible_env.HOME }}/.icons/"

- name: download gnome terminal theme dracula
  git:
    repo: git@github.com:dracula/gnome-terminal.git
    dest: "{{ ansible_env.HOME }}{{ clone_dir }}/theme/gnome-terminal-dracula"

- name: install san francisco font
  unarchive:
    src: fonts/SanFranciscoFonts.tar.gz
    dest: "{{ ansible_env.HOME }}{{ font_dir }}"
  notify:
    - rebuild font cache

- name: create folder for source code pro
  file:
    path: "{{ ansible_env.HOME }}{{ clone_dir }}/fonts/source-code-pro"
    state: directory

- name: download source code pro font
  unarchive:
    src: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: "{{ ansible_env.HOME }}{{ clone_dir }}/fonts/source-code-pro"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: install source code pro font
  shell: "cp {{ ansible_env.HOME }}{{ clone_dir }}/fonts/source-code-pro/OTF/* {{ ansible_env.HOME }}{{ font_dir }}"
  notify:
    - rebuild font cache

- name: config font preference
  copy:
    src: config/fontconfig/conf.d/64-language-selector-prefer.conf
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/conf.d/"
