---
- name: copy shell configs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/"
  with_fileglob:
    - home/.*

- name: install zplug
  git:
    repo: git clone https://github.com/zplug/zplug.git
    dest: "{{ ansible_env.HOME }}/.zplug"
    version: master

- name: install bash-it
  git:
    repo: git@github.com:Bash-it/bash-it.git
    dest: "{{ ansible_env.HOME }}/.bash_it"

- name: pull terminator
  command: bzr branch lp:terminator
  args:
    chdir: "{{ ansible_env.HOME }}/Develop/source"

- name: install terminator
  become: true
  command: ./setup.py install --record=install-files.txt
  args:
    chdir: "{{ ansible_env.HOME }}/Develop/source/terminator"

- name: config terminator
  copy:
    src: config/terminator/config
    dest: "{{ ansible_env.HOME }}/.config/terminator/"
