- name: add homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items: "{{ homebrew_taps }}"

- name: Upgrade all homebrew packages (if configured).
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install brew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default() }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ homebrew_packages }}"


- name: install brew cask packages
  tags: debug
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
  with_items: "{{ homebrew_cask_packages }}"

