---
- hosts: all

  vars_files:
    - common.config.yml

  pre_tasks:
    - include_vars: "{{ ansible_distribution }}.config.yml"

  roles:
    - { role: debian, when: ansible_distribution == 'Debian' }
    - { role: macos, when: ansible_distribution == 'MacOSX'}
    - common
