---
- hosts: all

  vars_files:
    - vars/common.yml
    - vars/user.yml

  pre_tasks:
    - include_vars: "vars/{{ ansible_distribution }}-{{ ansible_facts['distribution_major_version'] }}.yml"
      tags: always

  roles:
    - common
    - { role: debian, when: ansible_distribution == 'Debian' }
    - { role: macos, when: ansible_distribution == 'MacOSX'}
    - { role: arch, when: ansible_distribution == 'Archlinux'}
